---
on:
  - push

jobs:
  check:
    runs-on: ubuntu-latest
    name: Devbox Check
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7  # v0.15.0
      - name: Run devbox check
        run: devbox run check
