on: [push]

jobs:
  greenframe_action_workflow:
    runs-on: ubuntu-latest
    name: Run a GreenFrame CLI Action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all the git history to enable git comparison
      - name: GreenFrame Analysis
        uses: marmelab/greenframe-action@1.0.0
        env:
          GREENFRAME_SECRET_TOKEN: ${{secrets.GREENFRAME_SECRET_TOKEN}}
